name: Wickett
options:
  minimumXcodeGenVersion: 2.41.0
  deploymentTarget:
    iOS: 16.0
packages:
  privy-ios:
    url: https://github.com/privy-io/privy-ios.git
    from: 2.5.0
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.20.0
targets:
  Wickett:
    type: application
    platform: iOS
    entitlements:
      path: Resources/Wickett.entitlements
    sources:
      - path: Sources/Wickett
      - path: Resources
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.syndicatemike.Wickett
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: 5.7
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 3ZNP9JGQ38
          CODE_SIGN_IDENTITY: "Apple Development"
          OTHER_CODE_SIGN_FLAGS: "--deep"
    dependencies:
      - package: privy-ios
        product: Privy
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseFunctions
schemes:
  Wickett:
    build:
      targets:
        Wickett: all
    run:
      config: Debug

